CREATE TABLE IF NOT EXISTS kv_store_b75840fa (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
ALTER TABLE kv_store_b75840fa ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS allow_all ON kv_store_b75840fa;
CREATE POLICY allow_all ON kv_store_b75840fa FOR ALL TO anon USING (true) WITH CHECK (true);
